name: CI

on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install Antlr Runtime
        run: |
          pip install antlr4-python3-runtime 

      - name: install typeguard
        run: |
          pip install typeguard

      - name: install pytest
        run: |
          pip install pytest-golden

      - name: run tests
        run: |
          pytest --update-goldens golden-test.py

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          pip install poetry
          poetry install

      - name: check code formatting with Ruff
        run: poetry run ruff format --check .